version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: BatteryCommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"

  sua-aplicacao:
    image: battery-back:1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BatteryCommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
